[registries]
patina-fw = { index = "sparse+https://pkgs.dev.azure.com/patina-fw/artifacts/_packaging/temporary/Cargo/index/" }

# This tells cargo to consider the MSV of rust for our crate vs our dependencies
[resolver]
incompatible-rust-versions = "fallback"
