# @file ci-workflow.yml
#
# A workflow that runs basic CI tests and Rust CI tests, triggered on a pull_request or push to
# main.
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
##
name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci_workflow:
    name: Run
    uses: OpenDevicePartnership/patina-devops/.github/workflows/CiWorkflow.yml@v0.0.2
    secrets: inherit
    with:
      build-tasks: "build,build-x64,build-aarch64"
      run-cargo-vet: false
      run-release-dry-run: true
