name: Try and Create PR

on:
  workflow_dispatch

permissions:
  contents: write

jobs:
  create_pr:
    name: Create the PR

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Create Token
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.ODP_CICD_APPLICATION_CLIENT_ID }}
        private-key: ${{ secrets.ODP_CICD_APPLICATION_PRIVATE_KEY_BEGIN_END}}

    - name: Get GitHub App User ID
      id: get-user-id
      run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
    - run: |
        git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
        git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

    # git commands like commit work using the bot user
    - name: Push Branch
      run: |
        git checkout -b github-action/test-branch
        touch test.txt
        git add .
        git commit -m "Auto-generated changes"
        git push --set-upstream origin github-action/test-branch

    - name: Create PR (Fail)
      run: gh pr create --title "Auto-generated PR" --body "This PR was created by a GitHub Action" --base main --head github-action/test-branch
      env:
        GH_TOKEN: ${{ github.token }}
      continue-on-error: true

    - name: Create PR
      run: gh pr create --title "Auto-generated PR" --body "This PR was created by a GitHub Action" --base main --head github-action/test-branch
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
